server:
  port: 5000
spring:
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/chatbot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: tuanzi
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
chatbot:
  baseurl: http://api.qingyunke.com/api.php

logging:
  file:
    name: log/debug-file.log